config/routes.rb
Rails.application.routes.draw do
  get 'welcome/index'

  match 'feeds', to: 'feeds#index', via: [:options]
  match 'feeds/:id', to: 'feeds#show', via: [:options]
  match 'feeds/:id/articles', to: 'articles#index', via: [:options]
  match 'feeds/:id/articles/:id', to: 'articles#show', via: [:options]

  resources :feeds do
    resources :articles
  end

  root 'welcome#index'

end

app/models/article.rb
class Article < ActiveRecord::Base
  belongs_to :feed
  validates :title, presence: true
  validates :link, presence: true
  validates :content, presence: true
end

app/models/feed.rb
class Feed < ActiveRecord::Base
  has_many :articles, dependent: :destroy
  validates :title, presence: true
  validates :link, presence: true
  validates :author, presence: true
  validates :source, presence: true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception

  skip_before_filter :verify_authenticity_token
  before_filter :cors_preflight_check
  after_filter :cors_set_access_control_headers

  def cors_set_access_control_headers
    headers['Access-Control-Allow-Origin'] = '*'
    headers['Access-Control-Allow-Credentials'] = 'true'
    headers['Access-Control-Allow-Methods'] = 'POST, GET, PUT, DELETE, OPTIONS'
    headers['Access-Control-Allow-Headers'] = 'Origin, X-Requested-With, Content-Type, Accept, Authorization'
    headers['Access-Control-Max-Age'] = '1728000'
  end

  def cors_preflight_check
    if request.method == 'OPTIONS'
      headers['Access-Control-Allow-Origin'] = '*'
      headers['Access-Control-Allow-Credentials'] = 'true'
      headers['Access-Control-Allow-Methods'] = 'POST, GET, PUT, DELETE, OPTIONS'
      headers['Access-Control-Allow-Headers'] = 'Origin, X-Requested-With, Content-Type, Accept, Authorization'
      headers['Access-Control-Max-Age'] = '1728000'
    end
  end
end

app/controllers/articles_controller.rb
class ArticlesController < ApplicationController
  def create
    @feed = Feed.find(params[:feed_id])
    @article = @feed.articles.create(article_param)
    render json: @article
  end

  def show
    @article= Article.find(params[:id])
    respond_to do |format|
      format.json { render json: @article }
      format.xml { render xml: @article }
    end
  end

  def index
    @articles = Article.all
    respond_to do |format|
      format.json { render json: @articles }
      format.xml { render xml: @articles }
    end
  end

  def destroy
    @article = Article.find(params[:id]).destroy
    render nothing: true
  end

  private
  def article_param
    params.require(:article).permit(:title, :content, :link)
  end
end

app/controllers/feeds_controller.rb
class FeedsController < ApplicationController

  def new
  end

  def create
    @feed = Feed.create(feed_param)
    render json: @feed
  end

  def show
    @feed= Feed.find(params[:id])
    respond_to do |format|
      format.json { render json: @feed }
      format.xml { render xml: @feed }
    end
  end

  def index
    @feeds = Feed.all
    respond_to do |format|
      format.json { render json: @feeds }
      format.xml { render xml: @feeds }
    end
  end

  def destroy
    @feed = Feed.find(params[:id]).destroy
    render nothing: true
  end

  private
  def feed_param
    params.require(:feeds).permit(:title, :author, :link, :source)
  end
end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
  def index
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/articles_helper.rb
module ArticlesHelper
end

app/helpers/entries_helper.rb
module EntriesHelper
end

app/helpers/feed_helper.rb
module FeedHelper
end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/views/entries/new.html.erb
<h1>New Entry</h1>
<%= form_for :entry, url: entries_path do |f| %>
    <p>
      <%= f.label :id %><br>
      <%= f.text_field :e_id %>
    </p>

    <p>
      <%= f.label :title %><br>
      <%= f.text_field :title %>
    </p>
    <p>
      <%= f.label :link %><br>
      <%= f.text_field :link %>
    </p>

    <p>
      <%= f.label :content %><br>
      <%= f.text_area :content %>
    </p>

    <p>
      <%= f.submit %>
    </p>
<% end %>

app/views/feeds/index.html.erb
<h1>Listing articles</h1>

<table>
    <tr>
        <th>Title</th>
        <th>Text</th>
    </tr>

    <% @entries.each do |entry| %>
        <tr>
            <td><%= entry.title %></td>
            <td><%= entry.content %></td>
        </tr>
    <% end %>
</table>

app/views/feeds/new.html.erb
<h1>New Entry</h1>
<%= form_for :feeds, url: feeds_path do |f| %>

    <p>
      <%= f.label :title %><br>
      <%= f.text_field :title %>
    </p>
    <p>
      <%= f.label :link %><br>
      <%= f.text_field :link %>
    </p>

    <p>
      <%= f.label :author %><br>
      <%= f.text_field :author %>
    </p>

    <p>
      <%= f.label :source %><br>
      <%= f.text_field :source %>
    </p>

    <p>
      <%= f.submit %>
    </p>
<% end %>

app/views/feeds/show.html.erb
<p>
  <strong>Title:</strong>
  <%= @feed.title %>
</p>

<p>
  <strong>link:</strong>
  <%= @feed.link %>
</p>

<p>
  <strong>Author:</strong>
  <%= @feed.author %>
</p>

<h2>Entries</h2>

<% @feed.entries.each do |entry| %>
    <p>
      <strong>title:</strong>
      <%= entry.title %>
    </p>
    <p>
      <strong>link:</strong>
      <%= entry.link %>
    </p>
    <p>
      <strong>content:</strong>
      <%= entry.content %>
    </p>
<% end %>

<h2>Add a entry:</h2>
<%= form_for([@feed, @feed.entries.build]) do |f| %>
    <p>
      <%= f.label :title %><br>
      <%= f.text_field :title %>
    </p>
    <p>
      <%= f.label :link %><br>
      <%= f.text_field :link %>
    </p>
    <p>
      <%= f.label :content %><br>
      <%= f.text_area :content %>
    </p>
    <p>
      <%= f.submit %>
    </p>
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>FeedsServer</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>

</body>
</html>

app/views/welcome/index.html.erb
<h1>Feeds Reading System</h1>
<p>This is an open source project sponsored by Master Qiu</p>
<%= link_to 'My Blog', controller: 'feeds' %>